#Dependencies
from tkinter import Tk , Button , Canvas , Label , Entry , END
from tkinter.messagebox import showerror
from tkinter.filedialog import askopenfile , asksaveasfile

_VERSION = "1.0-stable"
_APPID = "TierlistTK"
_THEME = "dark"

root = Tk()
root.title("TierlistTK")
root.geometry("500x500")
root.resizable(False , False)
root.configure(bg="black")

canvas = Canvas(root , width=500 , height=500 , bg="grey15")
canvas.pack()

button1 = Button(root , text="Generate tierlist" , bg="darkorchid2" , fg="floralwhite" , font=("Fira Mono" , 12) , width=20)
button2 = Button(root , text="Settings" , bg="darkorchid2" , fg="floralwhite" , font=("Fira Mono" , 12) , width=20)
button3 = Button(root , text="Exit" , bg="firebrick2" , fg="white" , font=("Fira Mono" , 12) , width=20 , command=lambda:root.destroy())

entry1 = Entry(root , font=("Fira Mono" , 12))
entry2 = Entry(root , font=("Fira Mono" , 12))
titleentry = Entry(root , bg="grey15" , fg="floralwhite" , font=("Fira Mono" , 12))

entrys = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entrya = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryb = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryc = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryd = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")

label1 = Label(text="Enter the title of tierlist:-" , font=("Fira Mono" , 12) , bg="grey15" , fg="floralwhite")
label2 = Label(root, text=f"{_APPID}", font=("Fira Mono" , 12), bg="grey15", fg="floralwhite")
label3 = Label(root , text=f"Version:- {_VERSION}" , font=("Fira Mono" , 12), bg="grey15", fg="floralwhite")
label4 = Label(root , text="You are currently using the stable build" , font=("Fira Mono", 7) , bg="grey15" , fg="floralwhite")
label5 = Label(root , text="About App:-" , font=("Fira Mono" , 12 , "bold") , bg="grey15" , fg="floralwhite")
startinglabel = Label(text="Welcome to TierlistTK" , font=("Fira Mono" , 12 , "bold") , bg="grey15" , fg="darkorchid2")
applabel = Label(text="Appearance:-" , font=("Fira Mono" , 12 , "bold") , bg="grey15" , fg="floralwhite")

class Main():
    def starting():
        button = Button(root , text="Submit" , font=("Fira Mono" , 12) , bg="darkorchid2" , fg="floralwhite" , command=Main.get_title)
        if _THEME == "dark":
            button1 = Button(root , text="Open a tierlist.." , font=("Fira Mono" , 12) , bg="grey15" , fg="darkorchid2" , command=FileOperations.open)
            pass
        else:
            button1 = Button(root , text="Open a tierlist.." , font=("Fira Mono" , 12) , bg="floralwhite" , fg="darkorchid2" , command=FileOperations.open)
            pass
        canvas.delete('all')
        canvas.create_window(250 , 150, window=label1)
        canvas.create_window(250 , 200 , window=titleentry)
        canvas.create_window(250 , 250, window=button)
        canvas.create_window(250 , 400, window=button1)

    def get_title():
        global title
        title = titleentry.get()
        if title=="":
            showerror("Error" , "Please enter a title")
        else:
            root.title(f"{title} - TierlistTk")
            render_f()

class FileOperations():
    def save_f():
        tiercontent = f'''{title}
{entrys.get()}
{entrya.get()}
{entryb.get()}
{entryc.get()}
{entryd.get()}

Generated by TierlistTK \n'''

        file = asksaveasfile()
        try:
            file.write(tiercontent)
        except Exception:
            showerror("Error" , f"An Exception occured")

    def open():
        file = askopenfile("r+" , filetypes=[('Text Files' , '*.txtW')])
        entrys.delete(0 , END)
        entrya.delete(0 , END)
        entryb.delete(0 , END)
        entryc.delete(0 , END)
        entryd.delete(0 , END)
        content = file.read()
        content = list(content.splitlines())
        try:
            if content[7] == "Generated by TierlistTK ":
                root.title(f"{content[0]} - TierlistTK")
                entrys.insert(END,f"{content[1]}")
                entrya.insert(END,f"{content[2]}")
                entryb.insert(END,f"{content[3]}")
                entryc.insert(END,f"{content[4]}")
                entryd.insert(END,f"{content[5]}")
                render_f()
            else:
                showerror("Error" , "Invalid tierlist")
        except Exception:
            showerror("Error" , "An Exception occured")

buttonsave = Button(root , text="Save" , bg="darkorchid2" , fg="floralwhite" , command=FileOperations.save_f , font=("Fira Mono" , 12))
buttonopen = Button(root , text="Open" ,bg="darkorchid2" , fg="floralwhite" , command=FileOperations.open , font=("Fira Mono" , 12))

def homepage():
    canvas.delete("all")
    canvas.create_window(250 , 100, window=startinglabel)
    canvas.create_window(250 , 200, window=button1)
    canvas.create_window(250 , 250, window=button2)
    canvas.create_window(250 , 300, window=button3)

def render_f():
    canvas.delete("all")
    canvas.create_window(40 , 40, window=Button(root , text="S" , bg="coral1" , fg="black" , font=("Fira Mono", 14) , activebackground="coral1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 110, window=Button(root , text="A" , bg="tan1" , fg="black" , font=("Fira Mono", 14) , activebackground="tan1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 180 , window=Button(root , text="B" , bg="yellow1" , fg="black" , font=("Fira Mono", 14) , activebackground="yellow1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 250 , window=Button(root , text="C" , bg="lime" , fg="black" , font=("Fira Mono", 14) , activebackground="lime" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 320 , window=Button(root , text="D" , bg="cornflowerblue" , fg="black" , font=("Fira Mono", 14) , activebackground="cornflowerblue" , activeforeground="black"  , width=3 , height=2))
    canvas.create_window(290 , 40, window=entrys)
    canvas.create_window(290 , 110, window=entrya)
    canvas.create_window(290 ,180, window=entryb)
    canvas.create_window(290, 250 , window=entryc)
    canvas.create_window(290 , 320, window=entryd)

    canvas.create_window(200 , 400, window=buttonsave)
    buttonopen.configure(text="Open" ,bg="darkorchid2" , fg="floralwhite" )
    canvas.create_window(280 , 400, window=buttonopen)

def light_dark():
    global _THEME
    if _THEME == "dark":
        _THEME = "light"
        root.configure(bg="floralwhite")
        canvas.configure(bg="floralwhite")
        entrys.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        entrya.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        entryb.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        entryc.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        entryd.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        titleentry.configure(bg="floralwhite" , fg="grey15" , insertbackground="grey15")
        label1.configure(bg="floralwhite" , fg="grey15")
        label2.configure(bg="floralwhite" , fg="grey15")
        label3.configure(bg="floralwhite" , fg="grey15")
        label4.configure(bg="floralwhite" , fg="grey15")
        label5.configure(bg="floralwhite" , fg="grey15")
        startinglabel.configure(bg="floralwhite" , fg="grey15")
        applabel.configure(bg="floralwhite" , fg="grey15")
    else:
        _THEME = "dark"
        root.configure(bg="floralwhite")
        canvas.configure(bg="grey15")
        entrys.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        entrya.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        entryb.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        entryc.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        entryd.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        titleentry.configure(bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
        label1.configure(bg="grey15" , fg="floralwhite")
        label2.configure(bg="grey15" , fg="floralwhite")
        label3.configure(bg="grey15" , fg="floralwhite")
        label4.configure(bg="grey15" , fg="floralwhite")
        label5.configure(bg="grey15" , fg="floralwhite")
        startinglabel.configure(bg="grey15" , fg="grey15")
        applabel.configure(bg="grey15" , fg="floralwhite")

def settings():
    canvas.delete("all")
    canvas.create_window(50 , 50, window=Button(root , text="<-", bg="darkorchid2", fg="floralwhite", command=homepage))
    canvas.create_window(110 , 250, window=label5)
    canvas.create_window(100 , 300, window=label2)
    canvas.create_window(160 , 350, window=label3)
    canvas.create_window(250 , 475, window=label4)
    canvas.create_window(110 , 100, window=applabel)
    canvas.create_window(120 , 150, window=Button(root , text="Light/Dark Mode" , font=("Fira Mono" , 10) , bg="darkorchid2", fg="floralwhite", command=light_dark))

button1.configure(command=Main.starting)
button2.configure(command=settings)

homepage()

root.bind("<Control-o>" , lambda event:FileOperations.open())
root.bind("<Control-s>" , lambda event:FileOperations.save_f())

root.mainloop()
