#Dependencies
from tkinter import *
from tkinter.messagebox import showerror
from tkinter.filedialog import askopenfile , asksaveasfile

_VERSION = "1.0-build2"
_APPID = "TierlistTK"

root = Tk()
root.title("TierlistTK")
root.geometry("500x500")
root.resizable(False , False)
root.configure(bg="black")

canvas = Canvas(root , width=500 , height=500 , bg="grey15")
canvas.pack()

button1 = Button(root , text="Generate tierlist" , bg="darkorchid2" , fg="floralwhite" , font=("Fira Mono" , 12) , width=20)
button2 = Button(root , text="About TierlistTK" , bg="darkorchid2" , fg="floralwhite" , font=("Fira Mono" , 12) , width=20)
button3 = Button(root , text="Exit" , bg="firebrick2" , fg="white" , font=("Fira Mono" , 12) , width=20 , command=lambda:root.destroy())

entry1 = Entry(root , font=("Fira Mono" , 12))
entry2 = Entry(root , font=("Fira Mono" , 12))

entrys = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entrya = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryb = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryc = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")
entryd = Entry(root , font=("Fira Mono" , 30) , width=14 , bg="grey15" , fg="floralwhite" , insertbackground="floralwhite")

class Main():
    def starting():
        global titleentry
        titleentry = Entry(root , bg="grey15" , fg="floralwhite" , font=("Fira Mono" , 12))
        button = Button(root , text="Submit" , font=("Fira Mono" , 12) , bg="darkorchid2" , fg="floralwhite" , command=Main.get_title)
        button1 = Button(root , text="Open a tierlist.." , font=("Fira Mono" , 12) , bg="grey15" , fg="darkorchid2" , command=FileOperations.open)
        canvas.delete('all')
        canvas.create_window(250 , 150, window=Label(text="Enter the title of tierlist:-" , font=("Fira Mono" , 12) , bg="grey15" , fg="floralwhite"))
        canvas.create_window(250 , 200 , window=titleentry)
        canvas.create_window(250 , 250, window=button)
        canvas.create_window(250 , 400, window=button1)

    def get_title():
        global title
        title = titleentry.get()
        if title=="":
            showerror("Error" , "Please enter a title")
        else:
            root.title(f"{title} - TierlistTk")
            render_f()

class FileOperations():
    def save_f():
        tiercontent = f'''{title}
{entrys.get()}
{entrya.get()}
{entryb.get()}
{entryc.get()}
{entryd.get()}

Generated by TierlistTK \n'''

        file = asksaveasfile()
        try:
            file.write(tiercontent)
        except Exception:
            showerror("Error" , f"An Exception occured")

    def open():
        file = askopenfile("r+")
        entrys.delete(0 , END)
        entrya.delete(0 , END)
        entryb.delete(0 , END)
        entryc.delete(0 , END)
        entryd.delete(0 , END)
        content = file.read()
        content = list(content.splitlines())
        try:
            if content[7] == "Generated by TierlistTK ":
                root.title(f"{content[0]} - TierlistTK")
                entrys.insert(END,f"{content[1]}")
                entrya.insert(END,f"{content[2]}")
                entryb.insert(END,f"{content[3]}")
                entryc.insert(END,f"{content[4]}")
                entryd.insert(END,f"{content[5]}")
                render_f()
            else:
                showerror("Error" , "Invalid tierlist")
        except Exception:
            showerror("Error" , "An Exception occured")

buttonsave = Button(root , text="Save" , bg="darkorchid2" , fg="floralwhite" , command=FileOperations.save_f , font=("Fira Mono" , 12))
buttonopen = Button(root , text="Open" ,bg="darkorchid2" , fg="floralwhite" , command=FileOperations.open , font=("Fira Mono" , 12))

def homepage():
    canvas.delete("all")
    canvas.create_window(250 , 100, window=Label(root , text="Welcome to TierlistTk" , font=("Fira Mono" , 12) , fg="darkorchid2" , bg="grey15"))
    canvas.create_window(250 , 200, window=button1)
    canvas.create_window(250 , 250, window=button2)
    canvas.create_window(250 , 300, window=button3)

def render_f():
    canvas.delete("all")
    canvas.create_window(40 , 40, window=Button(root , text="S" , bg="coral1" , fg="black" , font=("Fira Mono", 14) , activebackground="coral1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 110, window=Button(root , text="A" , bg="tan1" , fg="black" , font=("Fira Mono", 14) , activebackground="tan1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 180 , window=Button(root , text="B" , bg="yellow1" , fg="black" , font=("Fira Mono", 14) , activebackground="yellow1" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 250 , window=Button(root , text="C" , bg="lime" , fg="black" , font=("Fira Mono", 14) , activebackground="lime" , activeforeground="black" , width=3 , height=2))
    canvas.create_window(40 , 320 , window=Button(root , text="D" , bg="cornflowerblue" , fg="black" , font=("Fira Mono", 14) , activebackground="cornflowerblue" , activeforeground="black"  , width=3 , height=2))
    canvas.create_window(290 , 40, window=entrys)
    canvas.create_window(290 , 110, window=entrya)
    canvas.create_window(290 ,180, window=entryb)
    canvas.create_window(290, 250 , window=entryc)
    canvas.create_window(290 , 320, window=entryd)

    canvas.create_window(200 , 400, window=buttonsave)
    buttonopen.configure(text="Open" ,bg="darkorchid2" , fg="floralwhite" )
    canvas.create_window(280 , 400, window=buttonopen)
def about_f():
    canvas.delete("all")
    canvas.create_window(50 , 50, window=Button(root , text="<-", bg="darkorchid2", fg="floralwhite", command=homepage))
    canvas.create_window(250 , 100, window=Label(root, text=f"{_APPID}", font=("Fira Mono" , 12), bg="grey15", fg="floralwhite"))
    canvas.create_window(250 , 150, window=Label(root , text=f"Version:- {_VERSION}" , font=("Fira Mono" , 12), bg="grey15", fg="floralwhite"))
    canvas.create_window(250 , 475, window=Label(root , text="You are currently using the developer build" , font=("Fira Mono", 7) , bg="grey15" , fg="floralwhite"))

button1.configure(command=Main.starting)
button2.configure(command=about_f)

homepage()

root.bind("<Control-o>" , lambda event:FileOperations.open())
root.bind("<Control-s>" , lambda event:FileOperations.save_f())

root.mainloop()
